/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.1804 from the
 * contents of main.xs. Do not edit this file, edit main.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "buildtmp\\\\main.xs"
/*
 * WARNING: This file was auto-generated. Changes will be lost!
 */

#include <cstring>
#include <cstdlib>
#include <ostream>

#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#undef do_open
#undef do_close
#ifdef __cplusplus
}
#endif

#line 32 "buildtmp\\XS.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 174 "buildtmp\\XS.c"

/* INCLUDE_COMMAND:  Including output of 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp"' from 'main.xs' */

#include <exception>

#include <myinit.h>
#include "TriangleMesh.hpp"

XS_EUPXS(XS_Slic3r__TriangleMesh__XS_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	TriangleMesh *	RETVAL;
#line 16 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      RETVAL = new TriangleMesh();
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 203 "buildtmp\\XS.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	TriangleMesh *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 30 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      delete THIS;
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 237 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ReadSTLFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ReadSTLFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, input_file");
    {
	TriangleMesh *	THIS;
	char*	input_file = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::ReadSTLFile() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 43 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      THIS->ReadSTLFile( input_file );
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 271 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ReadFromPerl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ReadFromPerl)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "THIS, vertices, facets");
    {
	TriangleMesh *	THIS;
	SV*	vertices = ST(1)
;
	SV*	facets = ST(2)
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::ReadFromPerl() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 56 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      THIS->ReadFromPerl( vertices, facets );
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 307 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_Repair); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_Repair)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	TriangleMesh *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::Repair() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 69 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      THIS->Repair();
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 339 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_WriteOBJFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_WriteOBJFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "THIS, output_file");
    {
	TriangleMesh *	THIS;
	char*	output_file = (char *)SvPV_nolen(ST(1))
;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::WriteOBJFile() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 82 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      THIS->WriteOBJFile( output_file );
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 373 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ToPerl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_ToPerl)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	TriangleMesh *	THIS;
	AV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::ToPerl() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 95 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    try {
      RETVAL = THIS->ToPerl();
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 406 "buildtmp\\XS.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_stats); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_stats)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	TriangleMesh *	THIS;
	SV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (TriangleMesh *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::TriangleMesh::XS::stats() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 111 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
        HV* hv = newHV();
        (void)hv_stores( hv, "number_of_facets",    newSViv(THIS->stl.stats.number_of_facets) );
        (void)hv_stores( hv, "number_of_parts",     newSViv(THIS->stl.stats.number_of_parts) );
        (void)hv_stores( hv, "volume",              newSVnv(THIS->stl.stats.volume) );
        (void)hv_stores( hv, "degenerate_facets",   newSViv(THIS->stl.stats.degenerate_facets) );
        (void)hv_stores( hv, "edges_fixed",         newSViv(THIS->stl.stats.edges_fixed) );
        (void)hv_stores( hv, "facets_removed",      newSViv(THIS->stl.stats.facets_removed) );
        (void)hv_stores( hv, "facets_added",        newSViv(THIS->stl.stats.facets_added) );
        (void)hv_stores( hv, "facets_reversed",     newSViv(THIS->stl.stats.facets_reversed) );
        (void)hv_stores( hv, "backwards_edges",     newSViv(THIS->stl.stats.backwards_edges) );
        (void)hv_stores( hv, "normals_fixed",       newSViv(THIS->stl.stats.normals_fixed) );
        RETVAL = (SV*)newRV_noinc((SV*)hv);
#line 444 "buildtmp\\XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__TriangleMesh__XS_hello_world); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__TriangleMesh__XS_hello_world)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	std::string	RETVAL;
#line 137 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp\""
    RETVAL = "Hello world!";
#line 462 "buildtmp\\XS.c"
    ST(0) = newSVpvn( RETVAL.c_str(), RETVAL.length() );
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


/* INCLUDE: Returning to 'main.xs' from 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/TriangleMesh.xsp"' */


/* INCLUDE_COMMAND:  Including output of 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp"' from 'main.xs' */

#include <exception>

#include <myinit.h>
#include "Point.hpp"

XS_EUPXS(XS_Slic3r__Point__XS_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Point__XS_new)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 3)
       croak_xs_usage(cv,  "CLASS, _x= 0, _y= 0");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	Point *	RETVAL;
	unsigned long	_x;
	unsigned long	_y;

	if (items < 2)
	    _x = 0;
	else {
	    _x = (unsigned long)SvUV(ST(1))
;
	}

	if (items < 3)
	    _y = 0;
	else {
	    _y = (unsigned long)SvUV(ST(2))
;
	}
#line 16 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp\""
    try {
      RETVAL = new Point( _x, _y );
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 516 "buildtmp\\XS.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__Point__XS_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Point__XS_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Point *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Point *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Point::XS::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 30 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp\""
    try {
      delete THIS;
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 550 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__Point__XS_arrayref); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Point__XS_arrayref)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	Point *	THIS;
	SV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (Point *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Point::XS::arrayref() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 45 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp\""
        RETVAL = point2perl(*THIS);
#line 575 "buildtmp\\XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__Point__XS_hello_world); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Point__XS_hello_world)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	std::string	RETVAL;
#line 60 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp\""
    RETVAL = "Hello world!";
#line 593 "buildtmp\\XS.c"
    ST(0) = newSVpvn( RETVAL.c_str(), RETVAL.length() );
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


/* INCLUDE: Returning to 'main.xs' from 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Point.xsp"' */


/* INCLUDE_COMMAND:  Including output of 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp"' from 'main.xs' */

#include <exception>

#include <myinit.h>
#include "ZTable.hpp"
#include <vector>
#include <algorithm>

XS_EUPXS(XS_Slic3r__Object__XS__ZTable_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Object__XS__ZTable_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, z_array");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	ZTable *	RETVAL;
	std::vector< unsigned int >*	z_array;

	if (SvROK(ST(1)) && SvTYPE(SvRV(ST(1)))==SVt_PVAV) {
	  AV* av = (AV*)SvRV(ST(1));
	  const unsigned int len = av_len(av)+1;
	  z_array = new std::vector<unsigned int>(len);
	  SV** elem;
	  for (unsigned int i = 0; i < len; i++) {
	    elem = av_fetch(av, i, 0);
	    if (elem != NULL)
	      (*z_array)[i] = SvUV(*elem);
	    else
	      (*z_array)[i] = 0.;
	  }
	}
	else
	  Perl_croak(aTHX_ "%s: %s is not an array reference",
	             "Slic3r::Object::XS::ZTable::new",
	             "z_array")
;
#line 18 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp\""
    try {
      RETVAL = new ZTable( z_array );
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 653 "buildtmp\\XS.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__Object__XS__ZTable_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Object__XS__ZTable_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	ZTable *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ZTable *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Object::XS::ZTable::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 32 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp\""
    try {
      delete THIS;
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 687 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__Object__XS__ZTable_get_range); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Object__XS__ZTable_get_range)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "THIS, min_z, max_z");
    {
	ZTable*	THIS;
	unsigned int	min_z = (unsigned int)SvUV(ST(1))
;
	unsigned int	max_z = (unsigned int)SvUV(ST(2))
;
	std::vector<unsigned int>	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ZTable *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Object::XS::ZTable::get_range() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 49 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp\""
        RETVAL.resize(2);

        unsigned int bottom = 0;
        unsigned int top = THIS->z.size()-1;
        while (1) {
            unsigned int mid = bottom + floor((top - bottom)/2.0);
            if (mid == top || mid == bottom) {
                RETVAL[0] = mid;
                break;
            }
            if (THIS->z[mid] > min_z) {
                top = mid;
            } else {
                bottom = mid;
            }
        }
        top = THIS->z.size()-1;
        while (1) {
            unsigned int mid = bottom + ceil((top - bottom)/2.0);
            if (mid == top || mid == bottom) {
                RETVAL[1] = mid;
                break;
            }
            if (THIS->z[mid] < max_z) {
                bottom = mid;
            } else {
                top = mid;
            }
        }
#line 744 "buildtmp\\XS.c"
	ST(0) = sv_newmortal();
	AV* av = newAV();
	ST(0) = newRV_noinc((SV*)av);
	const unsigned int len = RETVAL.size();
	av_extend(av, len-1);
	for (unsigned int i = 0; i < len; i++) {
	  av_store(av, i, newSVuv(RETVAL[i]));
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__Object__XS__ZTable_lower_bound); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Object__XS__ZTable_lower_bound)
{
    dVAR; dXSARGS;
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "THIS, z, offset = 0");
    {
	unsigned int	z = (unsigned int)SvUV(ST(1))
;
	unsigned int	offset;
	ZTable *	THIS;
	unsigned int	RETVAL;
	dXSTARG;

	if (items < 3)
	    offset = 0;
	else {
	    offset = (unsigned int)SvUV(ST(2))
;
	}

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ZTable *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Object::XS::ZTable::lower_bound() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 86 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp\""
        RETVAL = std::lower_bound(THIS->z.begin() + offset, THIS->z.end(), z) - THIS->z.begin();
#line 788 "buildtmp\\XS.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__Object__XS__ZTable_upper_bound); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__Object__XS__ZTable_upper_bound)
{
    dVAR; dXSARGS;
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "THIS, z, offset = 0");
    {
	unsigned int	z = (unsigned int)SvUV(ST(1))
;
	unsigned int	offset;
	ZTable *	THIS;
	unsigned int	RETVAL;
	dXSTARG;

	if (items < 3)
	    offset = 0;
	else {
	    offset = (unsigned int)SvUV(ST(2))
;
	}

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ZTable *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::Object::XS::ZTable::upper_bound() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 95 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp\""
        RETVAL = std::upper_bound(THIS->z.begin() + offset, THIS->z.end(), z) - THIS->z.begin();
#line 825 "buildtmp\\XS.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#include <myinit.h>
#include <vector>

/* INCLUDE: Returning to 'main.xs' from 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/Object.xsp"' */


/* INCLUDE_COMMAND:  Including output of 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/XS.xsp"' from 'main.xs' */

#include <exception>

#include <myinit.h>

/* INCLUDE: Returning to 'main.xs' from 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/XS.xsp"' */


/* INCLUDE_COMMAND:  Including output of 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp"' from 'main.xs' */

#include <exception>

#include <myinit.h>
#include "ExPolygon.hpp"

XS_EUPXS(XS_Slic3r__ExPolygon__XS_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__ExPolygon__XS_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	ExPolygon *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ExPolygon *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::ExPolygon::XS::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 16 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp\""
    try {
      delete THIS;
    }
    catch (std::exception& e) {
      croak("Caught C++ exception of type or derived from 'std::exception': %s", e.what());
    }
    catch (...) {
      croak("Caught C++ exception of unknown type");
    }
#line 879 "buildtmp\\XS.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Slic3r__ExPolygon__XS_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__ExPolygon__XS_new)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "CLASS, ...");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	ExPolygon *	RETVAL;
#line 31 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp\""
        RETVAL = new ExPolygon ();
        // ST(0) is class name, ST(1) is contour and others are holes
        perl2polygon(ST(1), RETVAL->contour);
        RETVAL->holes.resize(items-2);
        for (unsigned int i = 2; i < items; i++) {
            perl2polygon(ST(i), RETVAL->holes[i-2]);
        }
#line 903 "buildtmp\\XS.c"
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__ExPolygon__XS_arrayref); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__ExPolygon__XS_arrayref)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	ExPolygon *	THIS;
	SV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (ExPolygon *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Slic3r::ExPolygon::XS::arrayref() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	}
;
#line 44 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp\""
        const unsigned int num_holes = THIS->holes.size();
        AV* av = newAV();
        av_fill(av, num_holes);  // -1 +1
        av_store(av, 0, polygon2perl(THIS->contour));
        for (unsigned int i = 0; i < num_holes; i++) {
            av_store(av, i+1, polygon2perl(THIS->holes[i]));
        }
        RETVAL = (SV*)newRV_noinc((SV*)av);
#line 937 "buildtmp\\XS.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Slic3r__ExPolygon__XS_hello_world); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Slic3r__ExPolygon__XS_hello_world)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	std::string	RETVAL;
#line 66 "C:\\\\Dwimperl\\\\perl\\\\bin\\\\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt\"  \"C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp\""
    RETVAL = "Hello world!";
#line 955 "buildtmp\\XS.c"
    ST(0) = newSVpvn( RETVAL.c_str(), RETVAL.length() );
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


/* INCLUDE: Returning to 'main.xs' from 'C:\Dwimperl\perl\bin\perl.exe -MExtUtils::XSpp::Cmd -e xspp -- -t "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/typemap.xspt"  "C:/Users/Daniel-STP/Documents/GitHub/Slic3rTraduit/xs/xsp/ExPolygon.xsp"' */

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Slic3r__XS); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Slic3r__XS)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Slic3r::TriangleMesh::XS::new", XS_Slic3r__TriangleMesh__XS_new, file);
        newXS("Slic3r::TriangleMesh::XS::DESTROY", XS_Slic3r__TriangleMesh__XS_DESTROY, file);
        newXS("Slic3r::TriangleMesh::XS::ReadSTLFile", XS_Slic3r__TriangleMesh__XS_ReadSTLFile, file);
        newXS("Slic3r::TriangleMesh::XS::ReadFromPerl", XS_Slic3r__TriangleMesh__XS_ReadFromPerl, file);
        newXS("Slic3r::TriangleMesh::XS::Repair", XS_Slic3r__TriangleMesh__XS_Repair, file);
        newXS("Slic3r::TriangleMesh::XS::WriteOBJFile", XS_Slic3r__TriangleMesh__XS_WriteOBJFile, file);
        newXS("Slic3r::TriangleMesh::XS::ToPerl", XS_Slic3r__TriangleMesh__XS_ToPerl, file);
        newXS("Slic3r::TriangleMesh::XS::stats", XS_Slic3r__TriangleMesh__XS_stats, file);
        newXS("Slic3r::TriangleMesh::XS::hello_world", XS_Slic3r__TriangleMesh__XS_hello_world, file);
        newXS("Slic3r::Point::XS::new", XS_Slic3r__Point__XS_new, file);
        newXS("Slic3r::Point::XS::DESTROY", XS_Slic3r__Point__XS_DESTROY, file);
        newXS("Slic3r::Point::XS::arrayref", XS_Slic3r__Point__XS_arrayref, file);
        newXS("Slic3r::Point::XS::hello_world", XS_Slic3r__Point__XS_hello_world, file);
        newXS("Slic3r::Object::XS::ZTable::new", XS_Slic3r__Object__XS__ZTable_new, file);
        newXS("Slic3r::Object::XS::ZTable::DESTROY", XS_Slic3r__Object__XS__ZTable_DESTROY, file);
        newXS("Slic3r::Object::XS::ZTable::get_range", XS_Slic3r__Object__XS__ZTable_get_range, file);
        newXS("Slic3r::Object::XS::ZTable::lower_bound", XS_Slic3r__Object__XS__ZTable_lower_bound, file);
        newXS("Slic3r::Object::XS::ZTable::upper_bound", XS_Slic3r__Object__XS__ZTable_upper_bound, file);
        newXS("Slic3r::ExPolygon::XS::DESTROY", XS_Slic3r__ExPolygon__XS_DESTROY, file);
        newXS("Slic3r::ExPolygon::XS::new", XS_Slic3r__ExPolygon__XS_new, file);
        newXS("Slic3r::ExPolygon::XS::arrayref", XS_Slic3r__ExPolygon__XS_arrayref, file);
        newXS("Slic3r::ExPolygon::XS::hello_world", XS_Slic3r__ExPolygon__XS_hello_world, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

